module.exports = {
  manage: {
    open: 'app.userList.userOptions.manageUsersLabel',
    clear: 'USER MANAGE CLEAR ARIA LABEL',
    lock: 'USER MANAGE LOCK ARIA LABEL',
  },
  present: 'USER PRESENT ARIA LABEL',
  promote: 'USER PROMOTE ARIA LABEL',
  demote: 'USER DEMOTE ARIA LABEL',
  status: {
    open: 'USER STATUS OPEN ARIA LABEL',
    away: 'USER STATUS AWAY ARIA LABEL',
    hand: 'USER STATUS HAND ARIA LABEL',
    undecided: 'USER STATUS UNDECIDED ARIA LABEL',
    confused: 'USER STATUS CONFUSED ARIA LABEL',
    sad: 'USER STATUS SAD ARIA LABEL',
    happy: 'USER STATUS HAPPY ARIA LABEL',
    applaud: 'USER STATUS APPLAUD ARIA LABEL',
    up: 'USER STATUS UP ARIA LABEL',
    down: 'USER STATUS DOWN ARIA LABEL',
    clear: 'USER STATUS CLEAR ARIA LABEL',
  },
  name: {
    away: 'USER NAME AWAY ARIA LABEL',
    hand: 'USER NAME HAND ARIA LABEL',
    undecided: 'USER NAME UNDECIDED ARIA LABEL',
    confused: 'USER NAME CONFUSED ARIA LABEL',
    sad: 'USER NAME SAD ARIA LABEL',
    happy: 'USER NAME HAPPY ARIA LABEL',
    applaud: 'USER NAME APPLAUD ARIA LABEL',
    up: 'USER NAME UP ARIA LABEL',
    down: 'USER NAME DOWN ARIA LABEL',
    clear: 'USER NAME CLEAR ARIA LABEL',
    me: 'USER NAME ME ARIA LABEL',
    presenter: 'USER NAME PRESENTER ARIA LABEL',
  },
};
