module.exports = {
  board: 'WHITEBOARD BOARD ARIA LABEL',
  thickness: {
    open: 'app.whiteboard.toolbar.thickness',
    sizes: [
      'WHITEBOARD THICKNESS SIZE 1 ARIA LABEL',
      'WHITEBOARD THICKNESS SIZE 2 ARIA LABEL',
      'WHITEBOARD THICKNESS SIZE 4 ARIA LABEL',
      'WHITEBOARD THICKNESS SIZE 6 ARIA LABEL',
      'WHITEBOARD THICKNESS SIZE 8 ARIA LABEL',
      'WHITEBOARD THICKNESS SIZE 10 ARIA LABEL',
      'WHITEBOARD THICKNESS SIZE 12 ARIA LABEL',
      'WHITEBOARD THICKNESS SIZE 14 ARIA LABEL',
    ],
  },
  colors: {
    open: 'app.whiteboard.toolbar.color',
    palette: [
      'app.whiteboard.toolbar.color.black',
      'app.whiteboard.toolbar.color.white',
      'app.whiteboard.toolbar.color.red',
      'app.whiteboard.toolbar.color.orange',
      'app.whiteboard.toolbar.color.eletricLime',
      'app.whiteboard.toolbar.color.lime',
      'app.whiteboard.toolbar.color.cyan',
      'app.whiteboard.toolbar.color.dodgerBlue',
      'app.whiteboard.toolbar.color.blue',
      'app.whiteboard.toolbar.color.violet',
      'app.whiteboard.toolbar.color.magenta',
      'app.whiteboard.toolbar.color.silver',
    ],
  },
  tools: {
    open: 'app.whiteboard.toolbar.tools',
    text: 'app.whiteboard.toolbar.tools.text',
    line: 'app.whiteboard.toolbar.tools.line',
    ellipse: 'app.whiteboard.toolbar.tools.ellipse',
    triangle: 'app.whiteboard.toolbar.tools.triangle',
    rectangle: 'app.whiteboard.toolbar.tools.rectangle',
    pencil: 'app.whiteboard.toolbar.tools.pencil',
  },
  undo: 'app.whiteboard.toolbar.undo',
  clear: 'app.whiteboard.toolbar.clear',
  multi: {
    enable: 'app.whiteboard.toolbar.multiUserOn',
    disable: 'app.whiteboard.toolbar.multiUserOff',
  },
  toolbar: 'WHITEBOARD TOOLBAR ARIA LABEL',
};
