module.exports = {
  manage: {
    open: 'manageUsers',
    clear: '',
    lock: '',
  },
  present: 'takePresenter',
  promote: 'promoteToModerator',
  demote: 'demoteToViewer',
  status: {
    open: 'setStatus',
    away: 'away',
    hand: 'raiseHand',
    undecided: 'neutral',
    confused: 'confused',
    sad: 'sad',
    happy: 'happy',
    applaud: 'applause',
    up: 'thumbsUp',
    down: 'thumbsDown',
    clear: '',
  },
  name: {
    away: '',
    hand: '',
    undecided: '',
    confused: '',
    sad: '',
    happy: '',
    applaud: '',
    up: '',
    down: '',
    clear: '',
    me: '',
    presenter: '',
  },
};
