module.exports = {
  board: 'whiteboard',
  thickness: {
    open: '',
    sizes: [
      '1Tool',
      '2Tool',
      '4Tool',
      '6Tool',
      '8Tool',
      '10Tool',
      '12Tool',
      '14Tool',
    ],
  },
  colors: {
    open: '',
    palette: [
      '#c0c0c0Tool',
      '#ff00ffTool',
      '#8800ffTool',
      '#0000ffTool',
      '#0088ffTool',
      '#00ffffTool',
      '#00ff00Tool',
      '#ccff00Tool',
      '#ff8800Tool',
      '#ff0000Tool',
      '#ffffffTool',
      '#000000Tool',
    ],
  },
  tools: {
    open: 'toolsBtn',
    text: 'textTool',
    line: 'lineTool',
    ellipse: 'ellipseTool',
    triangle: 'triangleTool',
    rectangle: 'rectangleTool',
    pencil: 'pencilTool',
  },
  undo: '',
  clear: '',
  multi: {
    enable: 'turnMultiUsersWhiteboardOn',
    disable: 'turnMultiUsersWhiteboardOff',
  },
  toolbar: '',
};
